---
format: gfm
editor:
  markdown:
    wrap: 80
---

# Debugging

## Debugging an R package

In order to access debugging symbols, I created a new `Makevars` file within
the `ece244/src` folder, and added the following lines.

```bash
CXX_STD = CXX11
PKG_CPPFLAGS = -UDEBUG -g
```

Then I reinstalled the package compiled with debugging symbols, and in bash I
run `R -d lldb-11` to run the same benchmark as before.

I shouldn't generally leave the `-g` flag on in a Makevars file, that will
insert trace symbols in the compiled binary, both increasing compilation times
(often by a large margin), and creating larger binaries. Once the package is
compiled and I am sure that it works properly, I need to remove the
`PKG_CPPFLAGS = -UDEBUG -g` line.

## References

* [Debugging in R with a single command](https://mpadge.github.io/blog/blog012.html)
* [Debugging an R package with C++](https://blog.davisvaughan.com/posts/2019-04-05-debug-r-package-with-cpp/)
* [R's Makevars: PKG_CXXFLAGS vs. PKG_CXX11FLAGS](https://stackoverflow.com/questions/68959897/rs-makevars-pkg-cxxflags-vs-pkg-cxx11flags/68959927#68959927)
* [Debugging memory errors with valgrind and gdb](https://reside-ic.github.io/blog/debugging-memory-errors-with-valgrind-and-gdb/)
