// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
doubles_matrix<> transpose_(doubles_matrix<> X);
extern "C" SEXP _linalg_transpose_(SEXP X) {
  BEGIN_CPP11
    return cpp11::as_sexp(transpose_(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(X)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_linalg_transpose_", (DL_FUNC) &_linalg_transpose_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_linalg(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
