# Generated by cpp11: do not edit by hand

one_cpp_ <- function() {
  .Call(`_ece244_one_cpp_`)
}

sign_cpp_ <- function(x) {
  .Call(`_ece244_sign_cpp_`, x)
}

sum_cpp_ <- function(x) {
  .Call(`_ece244_sum_cpp_`, x)
}

pdist_cpp_ <- function(x, ys) {
  .Call(`_ece244_pdist_cpp_`, x, ys)
}

mean_cpp_ <- function(x) {
  .Call(`_ece244_mean_cpp_`, x)
}

cumsum_cpp_ <- function(x) {
  .Call(`_ece244_cumsum_cpp_`, x)
}

any_cpp_ <- function(x) {
  .Call(`_ece244_any_cpp_`, x)
}

which_cpp_ <- function(pred, x) {
  .Call(`_ece244_which_cpp_`, pred, x)
}
