# Generated by cpp11: do not edit by hand

one_cpp_ <- function() {
  .Call(`_ece244_one_cpp_`)
}

sign_cpp_ <- function(x) {
  .Call(`_ece244_sign_cpp_`, x)
}

sum_cpp_ <- function(x) {
  .Call(`_ece244_sum_cpp_`, x)
}

mean_cpp_ <- function(x) {
  .Call(`_ece244_mean_cpp_`, x)
}

rmse_cpp_ <- function(x, x0) {
  .Call(`_ece244_rmse_cpp_`, x, x0)
}

cumsum_cpp_ <- function(x) {
  .Call(`_ece244_cumsum_cpp_`, x)
}

any_cpp_ <- function(x) {
  .Call(`_ece244_any_cpp_`, x)
}

which_cpp_ <- function(pred, x) {
  .Call(`_ece244_which_cpp_`, pred, x)
}

all_cpp_4_ <- function(x) {
  .Call(`_ece244_all_cpp_4_`, x)
}

all_cpp_3_ <- function(x) {
  .Call(`_ece244_all_cpp_3_`, x)
}

all_cpp_2_ <- function(x) {
  .Call(`_ece244_all_cpp_2_`, x)
}

all_cpp_1_ <- function(x) {
  .Call(`_ece244_all_cpp_1_`, x)
}

cumprod_cpp_ <- function(x) {
  .Call(`_ece244_cumprod_cpp_`, x)
}

cumprod_cpp_2_ <- function(x) {
  .Call(`_ece244_cumprod_cpp_2_`, x)
}

cummin_cpp_ <- function(x) {
  .Call(`_ece244_cummin_cpp_`, x)
}

cummax_cpp_ <- function(x) {
  .Call(`_ece244_cummax_cpp_`, x)
}
